services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    env_file:
      - ./.env.development
    environment: &environment-definition
      NODE_ENV: development
      DB_HOST: "db" # must match the service name
      DB_USER: "sa"
      DB_PASSWORD: &password-definition "1m5ecure!"
      DB_NAME: "legal_files_development"
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
  test:
    build:
      context: .
      dockerfile: development.Dockerfile
    command: /bin/true
    env_file:
      - ./.env.development
    environment:
      <<: *environment-definition
      NODE_ENV: test
      DB_NAME: "legal_files_test"
    tty: true
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: *password-definition
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    tty: true
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    healthcheck: # https://github.com/Microsoft/mssql-docker/issues/133
      test: "/opt/mssql-tools/bin/sqlcmd -U sa -P \"$$SA_PASSWORD\" -Q \"SELECT 1\" || exit 1"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  db_data:
