services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    env_file:
      - ./.env.development
    environment:
      NODE_ENV: development
      DB_HOST: "localhost"
      DB_USER: "sa"
      DB_PASS: "1m5ecure!"
      DB_NAME: "LegalFiles"
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "1m5ecure!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  test:
    build:
      context: .
      dockerfile: development.Dockerfile
    command: /bin/true
    env_file:
      - ./.env.development
    environment:
      NODE_ENV: test
      DB_HOST: "localhost"
      DB_USER: "sa"
      DB_PASS: "1m5ecure!"
      DB_NAME: "LegalFilesTest"
    tty: true
    volumes:
      - .:/usr/src/app
