services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    env_file:
      - ./.env.development
    environment:
      NODE_ENV: development
      DB_HOST: "db" # must match the service name
      DB_USER: "sa"
      DB_PASSWORD: "1m5ecure!"
      DB_NAME: "legal_files_development"
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "1m5ecure!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    tty: true
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
  test:
    build:
      context: .
      dockerfile: development.Dockerfile
    command: /bin/true
    env_file:
      - ./.env.development
    environment:
      NODE_ENV: test
      DB_HOST: "db" # must match the service name
      DB_USER: "sa"
      DB_PASSWORD: "1m5ecure!"
      DB_NAME: "legal_files_test"
    tty: true
    volumes:
      - .:/usr/src/app

volumes:
  db_data:
