services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    ports:
      - '80:3000'
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "$DB_PASSWORD" # magic .env hoist
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - db_data:/var/opt/mssql
    healthcheck: # https://github.com/Microsoft/mssql-docker/issues/133
      test: "/opt/mssql-tools/bin/sqlcmd -U sa -P \"$$SA_PASSWORD\" -Q \"SELECT 1\" || exit 1"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  db_data:
